### ISSUE TITLE
Proposal for proton structure 

### ISSUE THREAD

**Issue by ravisuhag** [odpf/proton#23]
Proton is the central repository for all protobuf definitions. Which includes APIs, entities, events used across the entire ODPF ecosystem. To make the distinctions more clear. The following structure can be used. 

```
├── odpf
│   ├── entities
│   │   ├── README.md
│   │   ├── common
│   │   │   ├── event.proto
│   │   │   ├── resource.proto
│   │   │   └── timestamp.proto
│   │   ├── facets
│   │   │   ├── columns.proto
│   │   │   ├── lineage.proto
│   │   └── resources
│   │       ├── dashboard.proto
│   │       ├── group.proto
│   ├── apis
│   │   ├── guardian
│   │   │   ├── v1
│   │   │   |    ├── guardian.proto
│   │   ├── optimus
│   │   │   ├── v1
│   │   │   |    ├── guardian.proto
  
```
This will also allow package naming to be more consistent. 
`io.odpf.apis.guardian.v1`
`io.odpf.enttiies.resources.topic`
`io.odpf.events.metadata.optimusJob`

**Comment by kushsharma** [comment]
@ravisuhag can you maybe create a local directory and use `tree` to format the preview, looks a little confusing at the moment.
- How do we differentiate between `apis`, `entities` and `resources`? 
- Should we again create the same hierarchy as we have in `apis` in `resources` and `events`? Like `/odpf/events/optimus/v1`?

**Comment by ravisuhag** [comment]
@kushsharma updated.

**Comment by kushsharma** [comment]
Structure LGTM, although I think we can either name `entities` as just `metadata`(or something else) if that's the only thing we are using that folder for?

**Comment by rohilsurana** [comment]
As per the discussion we plan to remove the `odpf` directory from the root and bring all it's subdirs to the root of the repo -
```
.
├── LICENSE
├── README.md
├── buf.lock
├── buf.yaml
├── docs
├── assets
├── guardian
|   ├── v1alpha1
│   └── v1
├── metadata
├── optimus
│   └── v1
└── raccoon
    └── v1
```
And we would also be following directory and package based api versioning.

And these would be how our different package names would look like -
**Java -**
```
io.odpf.proton.guardian.v1
io.odpf.proton.optimus.v1
```

**Proto -**
```
odpf.guardian.v1
odpf.optimus.v1
```
**go -**
```
github.com/odpf/proton/guardian/v1
github.com/odpf/proton/optimus/v1
```

**Comment by kushsharma** [comment]
Is `assets` just an example or are going to use it for something?

**Comment by rohilsurana** [comment]
I brought the `assets` and `metadata` folders from the previous structure. These were under `odpf`, brought them out to root.
I think we can merge both of these into one.

**Comment by ravisuhag** [comment]
Wouldn't putting all at root will create noise? As `docs` `scripts` and others might exist at the root.
