### ISSUE TITLE
Push Protobuf schemas to buf.build

### ISSUE THREAD

**Issue by rohilsurana** [odpf/proton#35]
Push repo to [BSR](https://buf.build/) so it can be used for dependency in other Protobuf repos and for remote generation.

Also provide a way to access the generated BSR sequence ID so it can be used to generate the synthetic version used for importing remote generated packages.

**Comment by harikrishnakanchi** [comment]
Hey can we add steps for local dev setup?

**Comment by rohilsurana** [comment]
Let's create a separate issue for it.
We can discuss exactly what all needs to be there to better support local development.
